name: 'Kayobe run'
description: 'Runs Kayobe related commands'
inputs:
  script:
    description: 'Kayobe automation script to run'
    required: true
runs:
  using: composite
  steps:
    - run: ${{ github.action_path }}/${{ inputs.script }}
      shell: bash
