name: 'Kayobe run'
description: 'Runs Kayobe related commands'
inputs:
  script:
    description: 'Kayobe automation script to run'
    required: true
  kayobe-vault-password:
    description: 'Kayobe Ansible Vault password'
    required: true
  kayobe-automation-ssh-private-key:
    description: 'Kayobe automation SSH key'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.script }}
  env:
    KAYOBE_VAULT_PASSWORD: ${{ inputs.kayobe-vault-password }}
    KAYOBE_AUTOMATION_SSH_PRIVATE_KEY: ${{ inputs.kayobe-automation-ssh-private-key }}
